### ISSUE TITLE
Memory problem of post-processing step

### ISSUE THREAD

**Issue by thancaocuong** [batselem/human_pose_detection#1]
I've quickly reviewed your source code, so I think this line will caused memory leak problem. I think that you allocate memory for workspace but not release it at the end of process. 
https://github.com/batselem/human_pose_detection/blob/c9614378ef5d47ef7e1dbeb8ea83733db321e0a7/trt_demo/Openpose.cpp#L69
===
https://github.com/batselem/human_pose_detection/blob/c9614378ef5d47ef7e1dbeb8ea83733db321e0a7/trt_demo/Openpose.cpp#L87

**Comment by batselem** [comment]
Fixed the problem.
